#!/bin/bash
#
# Sets up the service dependancies
# Intended for Ubuntu 16.04 LTS

mkdir -p /var/log/tweets

# Install python3.6, nginx, and supervisor
add-apt-repository ppa:jonathonf/python-3.6 -y
apt-get update
apt-get install python3.6 -y

# Install pip for python3.6
curl "https://bootstrap.pypa.io/get-pip.py" -o "/tmp/get-pip.py"
python3.6 /tmp/get-pip.py

# Set up virtualenv
pip3.6 install virtualenv
virtualenv $(pwd)/.venv
source $(pwd)/.venv/bin/activate

# Get python dependancies
pip3.6 install -Ir $(pwd)/requirements.txt

# Link nginx config
ln -sf $(pwd)/prod/nginx.conf /etc/nginx/sites-available/quotes.pereira.io
ln -sf /etc/nginx/sites-available/quotes.pereira.io /etc/nginx/sites-enabled/quotes.pereira.io

# Link supervisor config
mkdir -p /var/log/quote-api
ln -sf $(pwd)/prod/supervisor.conf /etc/supervisor/conf.d/quotes.pereira.io.conf

# Start service
supervisorctl reread
supervisorctl update

# Reload nginx
nginx -s reload
